theme: jekyll-theme-cayman
title: Bioinformatics and data science blog
description: This blog describes use cases and challenges in the field of genomics and lifesciences.
minima:
  social_links:
    twitter: BioinformaticDS
    github: gtg269c
    linkedin: amin-momin
